<?php

return [
    ['m0' => 'm0_create_migration_history'],
    ['m1' => 'm1_create_admins_table'],
    ['m2' => 'm2_add_super_admin'],
    ['m3' => 'm3_create_countries_table'],
    ['m4' => 'm4_create_resorts_table'],
    ['m5' => 'm5_create_hotels_table'],
    ['m6' => 'm6_create_tours_table'],
    ['m7' => 'm7_create_managers_table'],
    ['m8' => 'm8_create_buses_table'],
    ['m9' => 'm9_create_clients_table'],
    ['m10' => 'm10_create_templates_table'],
    ['m11' => 'm11_create_rooms_table'],
    ['m12' => 'm12_create_subclients_table'],
    ['m13' => 'm13_create_contracts_table'],
    ['m14' => 'm14_create_clients_archive_table'],
    ['m15' => 'm15_create_tours_archive_table'],
    ['m16' => 'm16_create_subclients_archive_table'],
    ['m17' => 'm17_modify_tours_table_ownerTravelCost_column'],
    ['m18' => 'm18_modify_add_travel_service_column'],
    ['m19' => 'm19_modify_add_travel_cost_currency_1_column'],
    ['m20' => 'm20_modify_add_travel_cost_currency_2_column'],
    ['m21' => 'm21_modify_subclients_table_add_travel_service_column'],
    ['m22' => 'm22_modify_subclients_table_add_travel_cost_currency_1_column'],
    ['m23' => 'm23_modify_subclients_table_add_travel_cost_currency_2_column'],
    ['m24' => 'm24_modify_clients_and_subclients_tables_drop_archive_tables'],
    ['m25' => 'm25_create_table_stamps'],
];
